# License OCR Pipeline Configuration

# Input configuration
input:
  # Use one of the following:
  # image_path: "test_images/170349.jpg"  # Path to a single image file
  folder_path: "test_images"          # Path to a folder with multiple images

# Output configuration
output:
  result_file: "results.json"  # Path to the output JSON file

# YOLO model configuration
model:
  yolo_model_path: "best.pt"   # Path to YOLO model file
  license_class_id: 0          # Class ID for license component
  table_class_id: 1            # Class ID for table component

# OCR configuration
ocr:
  use_angle_cls: true          # Whether to use angle classification
  language: "en"               # OCR language
  use_gpu: false               # Whether to use GPU for OCR
  preprocessing_methods:       # List of preprocessing methods to apply
    - "gray"
    # - "adaptive_threshold"
    # - "denoise"
    # - "clahe"
    # - "hist_eq"

# Debug configuration
debug:
  save_intermediates: true     # Whether to save intermediate images
  output_dir: "debug_output"   # Directory for debug output

# Vehicle categories to look for
vehicle_categories:
  - "A1"
  - "A"
  - "B1"
  - "B"
  - "C1"
  - "C"
  - "CE"
  - "D1"
  - "D"
  - "DE"
  - "G1"
  - "G"
  - "J"
